In [18]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score, precision_score, classification_report 

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/rathch1/ML_BSCS/main/2.%20Logistic%20Regression/LR.csv")

In [4]:
data

Age  Salary  Purchased
0     19   19000          0
1     35   20000          0
2     26   43000          0
3     27   57000          0
4     19   76000          0
..   ...     ...        ...
395   46   41000          1
396   51   23000          1
397   50   20000          1
398   36   33000          0
399   49   36000          1

[400 rows x 3 columns]

In [5]:
data.shape

(400, 3)

In [6]:
data.describe()

Age         Salary   Purchased
count  400.000000     400.000000  400.000000
mean    37.655000   69742.500000    0.357500
std     10.482877   34096.960282    0.479864
min     18.000000   15000.000000    0.000000
25%     29.750000   43000.000000    0.000000
50%     37.000000   70000.000000    0.000000
75%     46.000000   88000.000000    1.000000
max     60.000000  150000.000000    1.000000

In [7]:
X = data.iloc[:,[0,1]].values
y = data.iloc[:, 2:].values

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [9]:
scaler = StandardScaler();
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
# using GaussianNB
classifier = GaussianNB()
classifier.fit(X_train_scaled, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

# Note
we were using X_test instead of X_test_scaled in the class that's why we were not getting model properly trained

In [11]:

y_pred = classifier.predict(X_test_scaled)

In [13]:
cm = confusion_matrix(y_test, y_pred)

In [14]:
cm

array([[50,  2],
       [ 3, 25]], dtype=int64)

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95        52
           1       0.93      0.89      0.91        28

    accuracy                           0.94        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80



# training model with MultinomialNB

In [21]:
mm_scaler = MinMaxScaler()

X_train_scaled = mm_scaler.fit_transform(X_train)
X_test_scaled = mm_scaler.transform(X_test)


In [22]:
# using MultinomilaNB
mnb_classifier = MultinomialNB()
mnb_classifier.fit(X_train_scaled, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [23]:
y_predict = mnb_classifier.predict(X_test_scaled)

In [24]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[50,  2],
       [ 3, 25]], dtype=int64)

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95        52
           1       0.93      0.89      0.91        28

    accuracy                           0.94        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80



# Training Model with BernoulliNB 

In [29]:
br_classifier = BernoulliNB()
br_classifier.fit(X_train_scaled, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB()

In [30]:
y_predict = br_classifier.predict(X_test_scaled)

In [31]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[50,  2],
       [ 3, 25]], dtype=int64)

In [32]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95        52
           1       0.93      0.89      0.91        28

    accuracy                           0.94        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80

