# Importing Liabraries

In [1]:
# importing liabraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split

# Loading Data

In [2]:
# Loading data
data =  pd.read_csv("https://raw.githubusercontent.com/rathch1/ML_BSCS/main/2.%20Logistic%20Regression/LR.csv")

In [3]:
data

Age  Salary  Purchased
0     19   19000          0
1     35   20000          0
2     26   43000          0
3     27   57000          0
4     19   76000          0
..   ...     ...        ...
395   46   41000          1
396   51   23000          1
397   50   20000          1
398   36   33000          0
399   49   36000          1

[400 rows x 3 columns]

In [6]:
# investigating first first five rows
data.head()

Age  Salary  Purchased
0   19   19000          0
1   35   20000          0
2   26   43000          0
3   27   57000          0
4   19   76000          0

In [7]:
# checking last five rows
data.tail()

Age  Salary  Purchased
395   46   41000          1
396   51   23000          1
397   50   20000          1
398   36   33000          0
399   49   36000          1

In [8]:
# Basic statistics for data
data.describe()

Age         Salary   Purchased
count  400.000000     400.000000  400.000000
mean    37.655000   69742.500000    0.357500
std     10.482877   34096.960282    0.479864
min     18.000000   15000.000000    0.000000
25%     29.750000   43000.000000    0.000000
50%     37.000000   70000.000000    0.000000
75%     46.000000   88000.000000    1.000000
max     60.000000  150000.000000    1.000000

# Splitting training and testing data

In [17]:
# gettting features and label
X = data.iloc[: , [0,1]]
y = data.iloc[: , 2 ]

(400,)

In [29]:
# splitting training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0   )

# StandardScalar 

In [30]:
# scalin values
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

X_test_scaled

array([[-7.98950822e-01,  4.94607583e-01],
       [-2.12648508e-02, -5.77359062e-01],
       [-3.12897090e-01,  1.46942725e-01],
       [-7.98950822e-01,  2.62831011e-01],
       [-3.12897090e-01, -5.77359062e-01],
       [-1.09058306e+00, -1.44652121e+00],
       [-7.01740076e-01, -1.59138156e+00],
       [-2.15686344e-01,  2.14601566e+00],
       [-1.96547978e+00, -5.58617754e-02],
       [ 8.53631867e-01, -7.80163563e-01],
       [-7.98950822e-01, -6.06331134e-01],
       [-9.93372315e-01, -4.32498705e-01],
       [-1.18475597e-01, -4.32498705e-01],
       [ 7.59458956e-02,  2.04886868e-01],
       [-1.77105829e+00,  4.65635512e-01],
       [-6.04529329e-01,  1.36376973e+00],
       [-1.18475597e-01,  2.04886868e-01],
       [-1.86826903e+00,  4.36663440e-01],
       [ 1.63131784e+00,  1.74040666e+00],
       [-3.12897090e-01, -1.38857706e+00],
       [-3.12897090e-01, -6.64275277e-01],
       [ 8.53631867e-01,  2.14601566e+00],
       [ 2.70367388e-01, -5.48386991e-01],
       [ 8.

# Building Model

In [32]:
# creating object of Logistic regression class
classifier = LogisticRegression(random_state=0)

In [33]:
# fitting the model
classifier.fit(X_train_scaled, y_train)

LogisticRegression(random_state=0)

In [34]:
# predicting values on X test scaled
y_pred = classifier.predict(X_test_scaled)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

# Model Evaluation

In [36]:
pd.DataFrame({'Y Test': y_test, 'Y Predict': y_pred})

Y Test  Y Predict
132       0          0
309       0          0
341       0          0
196       0          0
246       0          0
..      ...        ...
14        0          0
363       0          1
304       0          0
361       1          1
329       1          1

[80 rows x 2 columns]

In [37]:
# creating confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[57,  1],
       [ 5, 17]], dtype=int64)

In [38]:
# checking accuracy score
accuracy_score(y_test, y_pred)

0.925

In [39]:
# checking precision score
precision_score(y_test, y_pred)

0.9444444444444444

In [40]:
recall_score(y_test, y_pred)

0.7727272727272727

In [56]:
# predicting unkown number
classifier.predict([[31,100]])

array([1], dtype=int64)